import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";


const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	introduction: [{type: "autogenerated", dirName: "introduction"}],
	model: [{type: "autogenerated", dirName: "admin"}],
	commands: [{type: "autogenerated", dirName: "Usage"}],
  TOS: [{type: "doc", id: "TOS"}],
};

export default sidebars;
